FROM node:20-alpine

WORKDIR /app

COPY api-http/package*.json ./
RUN npm install -g json-server

COPY api-http/db.json .

EXPOSE 8081

CMD ["npx", "json-server", "--watch", "db.json", "--host", "0.0.0.0", "--port", "8081"]